services:
  task-api:
    build: .
    container_name: vtec_task_api
    ports:
      - "3050:3050"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://devuser:root_password@mysql:3306/calendar_todo
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./dist:/app/dist
      - ./node_modules:/app/node_modules
    networks:
      - infra-service_local_network

networks:
  infra-service_local_network:
    external: true
