services:
  task-api:
    build: .
    container_name: vtec_task_api_dev
    ports:
      - "3050:3050"
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://devuser:${MYSQL_PASSWORD}@mysql:3306/calendar_todo
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./dist:/app/dist
      - ./node_modules:/app/node_modules
    networks:
      - infra-service_dev_network

networks:
  infra-service_dev_network:
    external: true
